name: Docker Build and Push
on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
      - "backend/**"
jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest
    if: github.event.head_commit.modified[0] == 'frontend/'
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: dhairya07/quash-max-frontend:testV1
  build-and-push-backend:
    runs-on: ubuntu-latest
    if: github.event.head_commit.modified[0] == 'backend/'
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: dhairya07/quash-max-backend:testV1