name: Docker Build and Push

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
      - "backend/**"

jobs:
  determine-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend_changed: ${{ steps.check.outputs.frontend }}
      backend_changed: ${{ steps.check.outputs.backend }}
    steps:
      - uses: actions/checkout@v2
      - name: Check for frontend changes
        id: check
        uses: dorny/paths-filter@v2
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'

  build-and-push-frontend:
    if: ${{ needs.determine-changes.outputs.frontend_changed == 'true' }}
    runs-on: ubuntu-latest
    needs: determine-changes
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: dhairya07/quash-max-frontend:testV1

  build-and-push-backend:
    if: ${{ needs.determine-changes.outputs.backend_changed == 'true' }}
    runs-on: ubuntu-latest
    needs: determine-changes
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: dhairya07/quash-max-backend:testV1
