name: Docker Build and Push

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
      - "backend/**"

jobs:
  build-and-push-frontend:
    if: ${{ contains(toJson(github.event.commits.*.modified), 'frontend/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: dhairya07/quash-max-frontend:testV1

  build-and-push-backend:
    if: ${{ contains(toJson(github.event.commits.*.modified), 'backend/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: dhairya07/quash-max-backend:testV1
